[project]
name = "Hyperliquid Analysis"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.0",
    "pyarrow>=23.0.1",
    "seaborn>=0.13.2",
]
